### ISSUE TITLE
Compatible with python2.x ?

### ISSUE THREAD

**Issue by saddepal** [jd/git-pull-request#35]
Thanks for the tool. Is this compatible with both python2.x and python3 versions ?

I tried to use this for python2.x version. Getting parse not found error.

**Comment by jd** [comment]
No, see `setup.cfg` classifications.

**Comment by saddepal** [comment]
Thanks for the reply. Yes, I got it. Updated my local copy to fix this to support Python2.7. It would have been good if this can be compatible for both Python 2.x and 3.x versions.

Anyway thanks for the code.
