### ISSUE TITLE
getting this error fatal: 'pull-request' appears to be a git command, but we were not able to execute it. Maybe git-pull-request is broken?

### ISSUE THREAD

**Issue by markmark1** [jd/git-pull-request#38]
() $ git pull-request
fatal: 'pull-request' appears to be a git command, but we were not
able to execute it. Maybe git-pull-request is broken?

pip3 install git-pull-request
Requirement already satisfied: git-pull-request in /usr/local/lib/python3.6/site-packages (2.2.0)
Requirement already satisfied: daiquiri in /usr/local/lib/python3.6/site-packages (from git-pull-request) (1.2.1)
Requirement already satisfied: pygithub in /usr/local/lib/python3.6/site-packages (from git-pull-request) (1.35)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.6/site-packages (from pygithub->git-pull-request) (1.5.2)

**Comment by jd** [comment]
Do you have `/usr/local/bin/git-pull-request`?
did you try to start a new shell? Some shell as zsh needs `rehash` before they can see new commands.

**Comment by markmark1** [comment]
yes its available but not working /usr/local/bin/git-pull-request

**Comment by markmark1** [comment]
nothing added to commit but untracked files present
expansion of alias 'pr' failed; 'pull-request' is not a git command

**Comment by jd** [comment]
What happens if you run `/usr/local/bin/git-pull-request` ?

**Comment by markmark1** [comment]
/usr/local/bin/git-pull-request
-bash: /usr/local/bin/git-pull-request: /usr/local/opt/python3/bin/python3.6: bad interpreter: No such file or directory
~ $ unset PYTHONPATH
 ~ $ /usr/local/bin/git-pull-request
 /usr/local/opt/python3/bin/python3.6: bad interpreter: No such file or directory

**Comment by jd** [comment]
You clearly have a problem in your Python installation. You have a installed git-pull-request with a pip version that points to a Python setup that does not exist anymore.
Fix that first. Nothing wrong with git-p-r here.

**Comment by markmark1** [comment]
Thank you for your help. How do I fix that  
 
 
 

 
>  
>    
>
