### ISSUE TITLE
Allow to use a different GitHub endpoint

### ISSUE THREAD

**Issue by harlowja** [jd/git-pull-request#4]
It's a simple change, but let's me use my github enterprise that is used internally.

**Comment by jd** [comment]
Definitely! I did not know it was a thing :)

**Comment by jd** [comment]
@harlowja I've no idea what the URL look like in an entreprise edition so if that still does not work feel free to reopen and let me know what the URL looks like.

**Comment by vr** [comment]
Hey, it doesn't work because it search for github.com in ~/.netrc file, urls are the same, only the domain part change
