### ISSUE TITLE
Using git pull-request from bash script

### ISSUE THREAD

**Issue by Canisback** [jd/git-pull-request#44]
I've been using this to automate a pull request, but if it works well when I use it directly from command line, when I do it from a bash script, it says the git pull-requests command is not a git command.
I'm on Debian 8.

Any hint on how to make it work?

**Comment by jd** [comment]
Sounds like you did not install it correctly. Where's `git-pull-request`?

**Comment by Canisback** [comment]
It is in the directory where all my python3 modules are -> /usr/local/lib/python3.5/dist-packages

**Comment by Canisback** [comment]
This is where all the modules are installed with pip. And yes, I did use pip to install it.

**Comment by jd** [comment]
You should have a script in `/usr/local/bin/git-pull-request`. If that's not the case, reinstall. If so, check your `PATH` env var.

**Comment by Canisback** [comment]
There is indeed the script there too.

**Comment by jd** [comment]
So your bash script has a wrong `PATH` set likely. Just call `/usr/local/bin/git-pull-request` directly.
