### ISSUE TITLE
Support Github 2FA

### ISSUE THREAD

**Issue by anavarre** [jd/git-pull-request#8]
Thanks for letting me know about this tool! I just tried it and wondered how it'd play with 2FA. Turns out it doesn't seem to support it.

```
$ git pull-request
No target branch configured for local branch `improve-readme', using `master'.
Use the --target-branch option to override.
TwoFactorException: 401 {u'documentation_url': u'https://developer.github.com/v3/auth#working-with-two-factor-authentication', u'message': u'Must specify two-factor authentication OTP code.'}
```

The good news is Github's 2FA is not being bypassed. The bad news is I can't use this project. Would there be some way to ask for a challenge when running the `git pull-request` command?

**Comment by jd** [comment]
You can use it with 2FA, since I do. You just have to generate a unique token to use in your `~/.netrc`. See https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

**Comment by anavarre** [comment]
Thanks, this just works.
